### PR TITLE
Added function name for call stack clarity

### PR DESCRIPTION
**Pull request by jayphelps**

### CODE REVIEW

**Comment by rwjblue** [comment]
Awesome, thank you!

**Comment by jayphelps** [comment]
@rwjblue I wish there was a trivial way to also keep the entire `Ember.computed` namespace along with it.

``` js
import Ember from 'ember';
import computed from 'ember-new-computed';

export default Ember.Object.extend({
  foo: computed({
    get() {
      return 'whatever';
    }
  }),
  bar: computed.reads('foo')
});
```

We could have a hardcoded list of to pick from (yuck) or reach into the private `Ember.__loader.require('ember-metal/computed_macros')` to get the list....neither of which are ideal.

**Comment by rwjblue** [comment]
discussed solution for the last comment in slack, I believe PR is incoming

**Comment by rwjblue** [comment]
released in 1.0.1

**Pull request merged**
